resource "google_sql_database_instance" "main" {
  name             = "${local.prefix}-pg"
  region           = var.region
  database_version = "POSTGRES_16"

  # Every block, backup and WAL segment is encrypted under our own KMS key.
  # Destroying that key renders the instance permanently unreadable, which is
  # the "crypto-shred" lever for a full-tenant erasure request.
  encryption_key_name = google_kms_crypto_key.sql_cmek.id

  deletion_protection = var.db_deletion_protection

  settings {
    tier              = var.db_tier
    availability_type = var.db_availability_type
    disk_type         = "PD_SSD"
    disk_size         = var.db_disk_size_gb
    disk_autoresize   = true
    edition           = "ENTERPRISE"

    user_labels = local.labels

    ip_configuration {
      # No public IP. The instance is reachable only from the peered VPC.
      ipv4_enabled                                  = false
      private_network                               = google_compute_network.main.id
      enable_private_path_for_google_cloud_services = true
      ssl_mode                                      = "ENCRYPTED_ONLY"
    }

    backup_configuration {
      enabled                        = true
      start_time                     = "18:30" # 00:00 IST
      point_in_time_recovery_enabled = true
      transaction_log_retention_days = 7
      location                       = var.region

      backup_retention_settings {
        retained_backups = 30
        retention_unit   = "COUNT"
      }
    }

    maintenance_window {
      day          = 7 # Sunday
      hour         = 19
      update_track = "stable"
    }

    insights_config {
      query_insights_enabled = true
      # Query text is redacted of literals so PII cannot leak into Query Insights.
      record_application_tags = false
      record_client_address   = false
      query_string_length     = 1024
    }

    # --- Database flags: the security-relevant ones ---
    database_flags {
      # Turns on Cloud SQL IAM authentication. This is what allows the backend
      # to log in with an OAuth token instead of a stored password.
      name  = "cloudsql.iam_authentication"
      value = "on"
    }

    database_flags {
      name  = "log_min_duration_statement"
      value = "1000"
    }

    database_flags {
      name  = "log_connections"
      value = "on"
    }

    database_flags {
      name  = "log_disconnections"
      value = "on"
    }

    database_flags {
      name  = "log_checkpoints"
      value = "on"
    }

    database_flags {
      # Do not log statement text: it would put encrypted-PII parameters and
      # query literals into Cloud Logging, creating a second data store.
      name  = "log_statement"
      value = "ddl"
    }

    database_flags {
      name  = "max_connections"
      value = "200"
    }
  }

  depends_on = [
    google_service_networking_connection.private_vpc,
    google_kms_crypto_key_iam_member.sql_agent_cmek,
  ]

  lifecycle {
    prevent_destroy = true
  }
}

resource "google_sql_database" "kycvault" {
  name     = "kycvault"
  instance = google_sql_database_instance.main.name

  # Deterministic collation so index behaviour does not drift between
  # environments or after a restore.
  charset   = "UTF8"
  collation = "en_US.UTF8"
}

# --- IAM database users -----------------------------------------------------
# No passwords exist for these. Authentication is an OAuth2 access token minted
# by the metadata server and handed to Postgres by the Cloud SQL Auth Proxy.
resource "google_sql_user" "backend" {
  name     = local.db_iam_user
  instance = google_sql_database_instance.main.name
  type     = "CLOUD_IAM_SERVICE_ACCOUNT"
}

resource "google_sql_user" "migrator" {
  name     = trimsuffix(google_service_account.migrator.email, ".gserviceaccount.com")
  instance = google_sql_database_instance.main.name
  type     = "CLOUD_IAM_SERVICE_ACCOUNT"
}

# A break-glass built-in superuser, kept only because some Cloud SQL admin
# operations (extension installs, ownership fixes) still require a native role.
# The password is generated by Terraform, never printed, and stored in Secret
# Manager under CMEK. Rotate it after any use.
resource "random_password" "breakglass" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "google_sql_user" "breakglass" {
  name     = "kycvault_breakglass"
  instance = google_sql_database_instance.main.name
  password = random_password.breakglass.result
}
